// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacy.Data;

#nullable disable

namespace Pharmacy.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    partial class PharmacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pharmacy.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("username");

                    b.HasKey("AdminId")
                        .HasName("PK__admins__43AA4141A585EE2F");

                    b.HasIndex(new[] { "Email" }, "UQ__admins__AB6E6164FF3CA0A0")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__admins__F3DBC57214218078")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("Pharmacy.Models.AdminLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("ActionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("action_time")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action_type");

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.HasKey("LogId")
                        .HasName("PK__admin_lo__9E2397E0E51EA211");

                    b.HasIndex("AdminId");

                    b.ToTable("admin_logs", (string)null);
                });

            modelBuilder.Entity("Pharmacy.Models.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("drug_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("barcode");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DescriptionBeforeUse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_before_use");

                    b.Property<string>("DescriptionHowToUse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_how_to_use");

                    b.Property<string>("DescriptionSideEffects")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_side_effects");

                    b.Property<string>("DrugType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("drug_type");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("image_url");

                    b.Property<int>("LowAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("low_amount");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("PurchasingPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("purchasing_price");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("bit")
                        .HasColumnName("requires_prescription");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("selling_price");

                    b.Property<int>("ShelfAmount")
                        .HasColumnType("int")
                        .HasColumnName("shelf_amount");

                    b.Property<int>("StoredAmount")
                        .HasColumnType("int")
                        .HasColumnName("stored_amount");

                    b.Property<int>("SubAmountQuantity")
                        .HasColumnType("int")
                        .HasColumnName("sub_amount_quantity");

                    b.HasKey("DrugId")
                        .HasName("PK__drugs__73F2330CA7F8E910");

                    b.HasIndex(new[] { "Barcode" }, "UQ__drugs__C16E36F80ED4F771")
                        .IsUnique()
                        .HasFilter("[barcode] IS NOT NULL");

                    b.ToTable("drugs", (string)null);
                });

            modelBuilder.Entity("Pharmacy.Models.DrugTag", b =>
                {
                    b.Property<int>("DrugId")
                        .HasColumnType("int")
                        .HasColumnName("drug_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("DrugId", "TagId")
                        .HasName("PK__drug_tag__07DB5927FFBD29C7");

                    b.HasIndex("TagId");

                    b.ToTable("drug_tags", (string)null);
                });

            modelBuilder.Entity("Pharmacy.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount_paid");

                    b.Property<decimal>("ChangeAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("change_amount");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTime>("InvoiceTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_time")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.HasKey("InvoiceId")
                        .HasName("PK__invoices__F58DFD4921BD016E");

                    b.HasIndex("AdminId");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Pharmacy.Models.InvoiceItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("DrugId")
                        .HasColumnType("int")
                        .HasColumnName("drug_id");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("ItemId")
                        .HasName("PK__invoice___52020FDDA3592531");

                    b.HasIndex("DrugId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_items", (string)null);
                });

            modelBuilder.Entity("Pharmacy.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("TagId")
                        .HasName("PK__tags__4296A2B656706952");

                    b.HasIndex(new[] { "Name" }, "UQ__tags__72E12F1B6BE40C81")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Pharmacy.Models.AdminLog", b =>
                {
                    b.HasOne("Pharmacy.Models.Admin", "Admin")
                        .WithMany("AdminLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_logs_admin");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Pharmacy.Models.DrugTag", b =>
                {
                    b.HasOne("Pharmacy.Models.Drug", "Drug")
                        .WithMany("DrugTags")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dt_drug");

                    b.HasOne("Pharmacy.Models.Tag", "Tag")
                        .WithMany("DrugTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dt_tag");

                    b.Navigation("Drug");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Pharmacy.Models.Invoice", b =>
                {
                    b.HasOne("Pharmacy.Models.Admin", "Admin")
                        .WithMany("Invoices")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invoice_admin");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Pharmacy.Models.InvoiceItem", b =>
                {
                    b.HasOne("Pharmacy.Models.Drug", "Drug")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ii_drug");

                    b.HasOne("Pharmacy.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ii_invoice");

                    b.Navigation("Drug");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Pharmacy.Models.Admin", b =>
                {
                    b.Navigation("AdminLogs");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Pharmacy.Models.Drug", b =>
                {
                    b.Navigation("DrugTags");

                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("Pharmacy.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("Pharmacy.Models.Tag", b =>
                {
                    b.Navigation("DrugTags");
                });
#pragma warning restore 612, 618
        }
    }
}
